use crate::db::{backlinks, index, search};
use crate::DbState;
use serde::Serialize;

// ---------------------------------------------------------------------------
// Phase 3: Semantic Search Result Type
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize)]
pub struct SemanticSearchResult {
    /// Underlying FTS search result
    pub result: search::SearchResult,
    /// Semantic similarity score (0.0-1.0)
    pub semantic_score: f32,
    /// Mastery gap penalty (Phase 3 Prism feedback)
    pub mastery_gap: f32,
    /// Recency score (0.0-1.0, higher = more recent)
    pub recency_score: f32,
    /// Combined ranking score (semantic 50% + mastery_gap 30% + recency 10% + diversity 10%)
    pub combined_rank: f32,
}

// ---------------------------------------------------------------------------
// Existing Search Commands
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn search_notes(
    state: tauri::State<'_, DbState>,
    query: String,
    limit: usize,
) -> Result<Vec<search::SearchResult>, String> {
    let conn = state.0.lock().map_err(|e| format!("DB lock error: {e}"))?;
    search::search_notes(&conn, &query, limit)
}

#[tauri::command]
pub fn search_all(
    state: tauri::State<'_, DbState>,
    query: String,
    limit: usize,
) -> Result<Vec<search::SearchResult>, String> {
    let conn = state.0.lock().map_err(|e| format!("DB lock error: {e}"))?;
    search::search_all(&conn, &query, limit)
}

#[tauri::command]
pub fn reindex_vault(
    state: tauri::State<'_, DbState>,
    vault_path: String,
) -> Result<usize, String> {
    let conn = state.0.lock().map_err(|e| format!("DB lock error: {e}"))?;
    index::reindex_vault(&conn, &vault_path)
}

#[tauri::command]
pub fn get_backlinks(
    state: tauri::State<'_, DbState>,
    note_path: String,
) -> Result<Vec<backlinks::Backlink>, String> {
    let conn = state.0.lock().map_err(|e| format!("DB lock error: {e}"))?;
    backlinks::get_backlinks(&conn, &note_path)
}

// ---------------------------------------------------------------------------
// Phase 3: Semantic Search (Experimental)
// ---------------------------------------------------------------------------

/// Phase 3 semantic search prototype.
/// Combines FTS5 keyword search with semantic similarity ranking.
/// 
/// Implementation Plan:
/// 1. Query embedding generated by sentence-transformers sidecar (22MB, CPU-friendly)
/// 2. Semantic similarity computed against cached note embeddings (sqlite-vec)
/// 3. Combined ranking formula: semantic 50% + mastery_gap 30% + recency 10% + diversity 10%
/// 4. Confidence gate (0.65 threshold) enforced by Scout policy
/// 5. Fallback to FTS5 if semantic service unavailable
///
/// Dependencies:
/// - embedding_engine sidecar (backend/sidecars/embedding_engine/)
/// - note_embeddings table (Phase 3 schema migration)
/// - sqlite-vec extension for vector similarity
#[tauri::command]
pub fn search_semantic(
    state: tauri::State<'_, DbState>,
    query: String,
    limit: usize,
) -> Result<Vec<SemanticSearchResult>, String> {
    // Phase 3 TODO: Implement semantic search
    // For now, return empty results and a placeholder message
    // In production, this will:
    // 1. Call embedding_engine sidecar to generate query embedding
    // 2. Query sqlite-vec for top-K similar notes
    // 3. Rank by combined score (semantic + mastery + recency + diversity)
    // 4. Return results with confidence scores and source attribution
    
    let conn = state.0.lock().map_err(|e| format!("DB lock error: {e}"))?;
    
    // For now, fall back to FTS5 and wrap results with placeholder semantic scores
    let fts_results = search::search_all(&conn, &query, limit)?;
    
    let semantic_results: Vec<SemanticSearchResult> = fts_results
        .into_iter()
        .enumerate()
        .map(|(idx, result)| SemanticSearchResult {
            result,
            semantic_score: 0.85 - (idx as f32 * 0.05),  // Placeholder: decreasing scores
            mastery_gap: 0.0,  // TODO: Get from Prism mastery model
            recency_score: 0.5,  // TODO: Compute from modified_at
            combined_rank: 0.75,  // TODO: Compute weighted formula
        })
        .collect();
    
    Ok(semantic_results)
}
