"""
Tests for verify_numeric_question and validate_mc_question (Step 2a).

LLM calls are always mocked — no network access required.
"""
from __future__ import annotations

from unittest.mock import patch

import pytest


# ─── verify_numeric_question ──────────────────────────────────────────────────


def test_algebra_correct(study_engine_module):
    result = study_engine_module.verify_numeric_question(
        "Solve 2x + 4 = 10 for x", "3"
    )
    assert result["in_scope"] is True
    assert result["verified"] is True


def test_algebra_wrong_answer(study_engine_module):
    result = study_engine_module.verify_numeric_question(
        "Solve 2x + 4 = 10 for x", "5"
    )
    assert result["in_scope"] is True
    assert result["verified"] is False


def test_calculus_derivative_correct(study_engine_module):
    result = study_engine_module.verify_numeric_question(
        "Compute the derivative of x^3", "3*x**2"
    )
    assert result["in_scope"] is True
    assert result["verified"] is True


def test_out_of_scope_magnitude_response(study_engine_module):
    result = study_engine_module.verify_numeric_question(
        "Find the magnitude response of H(s) = 1/(s+1) at ω=10 rad/s",
        "0.0995",
    )
    assert result["in_scope"] is False
    assert result["verified"] is False


def test_sympy_error_path_no_crash(study_engine_module):
    """Malformed input must return verified=False without raising."""
    result = study_engine_module.verify_numeric_question(
        "Solve @@@@##$$ for x", "????"
    )
    assert result["verified"] is False
    assert "reason" in result
    # Must not raise; in_scope may be True or False depending on parse path.


# ─── validate_mc_question ─────────────────────────────────────────────────────

_CHOICES = ["A. 1", "B. 2", "C. 3", "D. 4"]
_CORRECT = "C. 3"
_QUESTION = "What is 1 + 2?"


def test_generation_openai_calls_ollama(study_engine_module):
    """When generated by OpenAI, validation must use Ollama, not OpenAI."""
    with patch.object(study_engine_module, "_ollama_chat", return_value="PASS") as mock_ollama, \
         patch.object(study_engine_module, "_openai_chat") as mock_openai:
        result = study_engine_module.validate_mc_question(
            _QUESTION,
            _CHOICES,
            _CORRECT,
            "openai",
            ollama_endpoint="http://localhost:11434",
            ollama_model="llama3.1:8b",
        )
    mock_ollama.assert_called_once()
    mock_openai.assert_not_called()
    assert result["validator"] == "ollama"


def test_generation_ollama_calls_openai(study_engine_module):
    """When generated by Ollama, validation must use OpenAI, not Ollama."""
    with patch.object(study_engine_module, "_openai_chat", return_value="PASS") as mock_openai, \
         patch.object(study_engine_module, "_ollama_chat") as mock_ollama:
        result = study_engine_module.validate_mc_question(
            _QUESTION,
            _CHOICES,
            _CORRECT,
            "ollama",
            openai_api_key="sk-test",
            openai_model="gpt-4o-mini",
        )
    mock_openai.assert_called_once()
    mock_ollama.assert_not_called()
    assert result["validator"] == "openai"


def test_validator_pass_response(study_engine_module):
    with patch.object(study_engine_module, "_openai_chat", return_value="PASS\n"):
        result = study_engine_module.validate_mc_question(
            _QUESTION, _CHOICES, _CORRECT, "ollama",
            openai_api_key="sk-test",
        )
    assert result["verified"] is True
    assert result["issues"] == []


def test_validator_fail_response_with_issues(study_engine_module):
    fail_body = "FAIL\nIssue 1\nIssue 2"
    with patch.object(study_engine_module, "_openai_chat", return_value=fail_body):
        result = study_engine_module.validate_mc_question(
            _QUESTION, _CHOICES, _CORRECT, "ollama",
            openai_api_key="sk-test",
        )
    assert result["verified"] is False
    assert result["issues"] == ["Issue 1", "Issue 2"]


def test_no_providers_available_openai_generator(study_engine_module):
    """No ollama config → no validator available when generator is openai."""
    result = study_engine_module.validate_mc_question(
        _QUESTION, _CHOICES, _CORRECT, "openai",
        ollama_endpoint="",
        ollama_model="",
    )
    assert result["verified"] is False
    assert result["validator"] == "none"
    assert "no cross-model validator available" in result["issues"]


def test_no_providers_available_ollama_generator(study_engine_module):
    """No openai_api_key → no validator available when generator is ollama."""
    result = study_engine_module.validate_mc_question(
        _QUESTION, _CHOICES, _CORRECT, "ollama",
        openai_api_key="",
    )
    assert result["verified"] is False
    assert result["validator"] == "none"
    assert "no cross-model validator available" in result["issues"]


def test_unknown_generation_provider(study_engine_module):
    result = study_engine_module.validate_mc_question(
        _QUESTION, _CHOICES, _CORRECT, "unknown_provider"
    )
    assert result["verified"] is False
    assert result["validator"] == "none"
